services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - EXNESS_ACCOUNT=${EXNESS_ACCOUNT}
      - EXNESS_PASSWORD=${EXNESS_PASSWORD}
      - EXNESS_SERVER=${EXNESS_SERVER}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - X_API_KEY=${X_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - COINBASE_API_KEY=${COINBASE_API_KEY}
      - FLUTTERWAVE_API_KEY=${FLUTTERWAVE_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE=${TWILIO_PHONE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}
      - ADMIN_URL=${ADMIN_URL}
      - OWNER_EMAIL=${OWNER_EMAIL}
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3