// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyxsotsoxyrpfkrfmdak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eHNvdHNveHlycGZrcmZtZGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDg2NjksImV4cCI6MjA2Njk4NDY2OX0.M0Y7CVK6_MzafKDmg0Af2qqIQXRpakFGxWfz5VP-C0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});